services:
  - type: web
    name: my-flask-app
    env: python
    pythonVersion: 3.9
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn PAWS_RUNNING_Game.app:app"
    staticPublishPath: static
    envVars:
      - key: PORT
        value: 5000
  
